apiVersion: v2
name: admin-hotlist
description: A Helm chart for MOSIP Admin Hotlist
type: application
version: 12.0.1-N1      
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - admin
  - hotlist
maintainers:
  - email: karthiksj70@gmail.com
    name: karthik
